### ISSUE TITLE
"No Pins" | Rock 5b+ | Ubuntu

### ISSUE THREAD

**Issue by divyansh-kumar** [eclipse-mraa/mraa#1134]
Hello everyone,
I am trying to install mraa on my rock5b+ which is running ubuntu 24.04, everything is working fine except the mraa.
I have followed this guide https://docs.radxa.com/en/rock5/rock5b/app-development/mraa?board=ROCK+5B%2B  
And have successfully compiled and installed mraa

With command `mraa-gpio version` it shows

`Version v2.2.0 on Unknown platform`

and `mraa-gpio list` shows `No Pins`

and because of that i cannot access it in my python code, which give me the error 

`rock5@rock5:~/Desktop$ sudo python3 blink.py 
Traceback (most recent call last):
  File "/home/rock5/Desktop/blink.py", line 5, in <module>
    gpio_1 = mraa.Gpio(23)
             ^^^^^^^^^
AttributeError: module 'mraa' has no attribute 'Gpio'`

can someone help me solve this

**Comment by alext-mkrs** [comment]
The reason is that 5B+ is not currently supported, though Radxa seem to have added it in [their fork](https://github.com/nascs/mraa/tree/Add_Radxa_ROCK5B%2B_Support) listed in that documentation you referenced.

@nascs, would you be interested in submitting a PR here upstreaming that?

**Comment by nascs** [comment]
ok, let me retest it.

**Comment by alext-mkrs** [comment]
@nascs, so have you had a chance to check it out?

**Comment by hiSandog** [comment]
Since Radxa's docs point at a fork with ROCK 5B+ support, this sounds like an upstreaming gap rather than a local install problem. It would help to know whether that fork's board detection works on a clean Ubuntu 24.04 image and what device-tree compatible strings it relies on. If the support is self-contained, a PR with the board definition plus a `mraa-gpio list` smoke output would likely be easier to review.

**Comment by alext-mkrs** [comment]
@nascs, pretty please? I generally only need a confirmation that the changes there are supposed to work (still) - I can port them back myself.

**Comment by nascs** [comment]
mraa is not worked with linux 6.1 for the pwm driver changed the pwmchip allocation logic.
